version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - "8090:80"
      - "9443:443"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mariadb
  php:
    volumes: 
      - ./website:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    build: .
  mariadb:
      image: mariadb:latest
      ports:
        - 3366:3306
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: Uoc1234U

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
         PMA_HOST: mariadb
         PMA_PORT: 3306
      ports:
        - '8181:80'
